CREATE DATABASE book;

USE book;

CREATE TABLE PUBLISHER (
	CODE VARCHAR(4) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (CODE)
);

CREATE TABLE BOOK (
	ISBN VARCHAR(50) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR VARCHAR(100) NOT NULL,
	YEAR INT NOT NULL,
	PUBLISHER_CODE VARCHAR(4),
	PRIMARY KEY (ISBN),
	FOREIGN KEY (PUBLISHER_CODE) REFERENCES PUBLISHER (CODE)
);
